
export const REQUEST_GET_AUTH_DAFAULT_LOGIN_ACTION = 'REQUEST_GET_AUTH_DAFAULT_LOGIN_ACTION'
export const REQUEST_POST_AUTH_DEFAULT_REG_ACTION = 'REQUEST_POST_AUTH_DEFAULT_REG_ACTION'

export const REQUEST_GET_USER_WHO_AM_I_ACTION = 'REQUEST_GET_USER_WHO_AM_I_ACTION'

export const SET_USER_TO_USER_REDUCE_ACTION = 'SET_USER_TO_USER_REDUCE_ACTION'

export const SET_NOTIFICATIONS_TO_USER_REDUCE_ACTION = 'SET_NOTIFICATIONS_TO_USER_REDUCE_ACTION'

export const REQUEST_GET_NOTIFICATIONS_ACTION = 'REQUEST_GET_NOTIFICATIONS_ACTION'

export const REQUEST_DELETE_NOTIFICATION_ACTION = 'REQUEST_DELETE_NOTIFICATION_ACTION'

export const SET_ALERT_TO_USER_REDUCE_ACTION = 'SET_ALERT_TO_USER_REDUCE_ACTION'

export const REQUEST_GET_TABLES_ACTION = 'REQUEST_GET_TABLES_ACTION'
export const REQUEST_POST_TABLE_ACTION = 'REQUEST_POST_TABLE_ACTION'
export const SET_TABLES_TO_TABLES_REDUCER_ACTION = 'SET_TABLES_TO_TABLES_REDUCER_ACTION'